version: '3.8'
services:
  oops_express:
    build: .
    ports:
      - 4000:4000
      - 9229:9229 # debug port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    environment:
      PORT: 3030
    restart: unless-stopped
  db:
    container_name: pg_container_
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"